//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Presidentes", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Presidentes : object
    {
        
        private string AntecedentesPolicialesField;
        
        private string ApellidosField;
        
        private string DNIField;
        
        private int IdPresidenteField;
        
        private string NombresField;
        
        private string PartidoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AntecedentesPoliciales
        {
            get
            {
                return this.AntecedentesPolicialesField;
            }
            set
            {
                this.AntecedentesPolicialesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPresidente
        {
            get
            {
                return this.IdPresidenteField;
            }
            set
            {
                this.IdPresidenteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partido
        {
            get
            {
                return this.PartidoField;
            }
            set
            {
                this.PartidoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServicePresidentes")]
    public interface IServicePresidentes
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePresidentes/GetPresidente", ReplyAction="http://tempuri.org/IServicePresidentes/GetPresidenteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Presidentes[]> GetPresidenteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicePresidentesChannel : ServiceReference1.IServicePresidentes, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicePresidentesClient : System.ServiceModel.ClientBase<ServiceReference1.IServicePresidentes>, ServiceReference1.IServicePresidentes
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicePresidentesClient() : 
                base(ServicePresidentesClient.GetDefaultBinding(), ServicePresidentesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicePresidentes.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePresidentesClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicePresidentesClient.GetBindingForEndpoint(endpointConfiguration), ServicePresidentesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePresidentesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicePresidentesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePresidentesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicePresidentesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicePresidentesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Presidentes[]> GetPresidenteAsync()
        {
            return base.Channel.GetPresidenteAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicePresidentes))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicePresidentes))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55771/ServicePresidente.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicePresidentesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicePresidentes);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicePresidentesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicePresidentes);
        }

        internal object GetPresidentesAsync()
        {
            throw new NotImplementedException();
        }

        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicePresidentes,
        }
    }
}
